### ISSUE TITLE
Feature Request: Quick Edit Mode 2.0

### ISSUE THREAD

**Issue by baileywick** [KayelGee/token-attacher#42]
Similar to how Levels module implemented a mode for restricting all tile placements, walls, drawings, etc to a specific level while building that level, it would  be nice if TA had a mode where, if I have the UI for a control token open, then any tiles I place, walls I draw, drawings, etc automatically attach to the control token. Instead of having to select them one-by-one or lasso them, (or forget to connect things).

**Comment by KayelGee** [comment]
I've had the dream that you could click somehow on the base token and that would make everything that's not part of the attachment chain invisible because you're looking inside the base token. Adding elements in this mode would only make sense to attach to the base token. I'm not sure how I would go about implementing that.

Your suggestion sounds way more doable. I'll have to think about how to add it to the ui or if it would make sense to make it only a macro like quick edit mode.

**Comment by baileywick** [comment]
Your vision sounds glorious. As for mine, Ripper will probably tell you how
he did it for Levels.

**Comment by KayelGee** [comment]
Added in next update. At least the light variant where everything will be attached while the attach ui is open.
