### ISSUE TITLE
Players receive "User <xxxxx> lacks permission to update Tokens in parent <XxXXxXxxxxXXxxXX>"

### ISSUE THREAD

**Issue by krobibero** [KayelGee/token-attacher#43]
I am running FVTT 7.9 with Token Attacher 4.0.2, and the game Starfinder system.  If I have attached tokens on the scene, my players receive "User <xxxxx> lacks permission to update Tokens in parent <XxXXxXxxxxXXxxXX>" error on their screen.  

Also, I'm testing with a blank player token as a "handle" for Token Attacher with a "Starship" actor token attached, and some light objects.  For some reason, the GM view shows the attached objects correctly and I can move the handle around without an issue and everything looks right.  On the player view (after receiving the above error) most of the attached lights do not move with the handle token, however the Starship token moves with the handle.

**Comment by KayelGee** [comment]
This has nothing to do with token attacher. That's a core bug of foundry 0.7.9(and presumably 0.7.10). This happens because you try to move multiple lights. Moving multiple lights(doesn't matter if it's through token attacher or not) will throw an exception on the players side which prevents the movements of all but one light.
