### ISSUE TITLE
Select and Assign a Pivot (feature request)

### ISSUE THREAD

**Issue by MarkPearce** [KayelGee/token-attacher#54]
Feature Request.

With vehicles and complicated rigs (eg bailywiki) it's common to use a controller token and link everything to that for moving large vehicles. But this leaves rotation at some strange offset outside the actual vehicle.

This is similar to the vehicles mod which lets you name a token in the scene to use as a pivot - BUT using a token actor is a poor choice as tokens within a vehicle are likely to overlap which risks accidently moving the pivot, or being unable to select a token due to zdepth layering problems. A shape or tile would be better, or even just enter an offset value in X/Y grid spaces.

Bonus points if when targeting a "controller" it can report its position as the pivot location, allowing players to utilize automation   in vehicle combat (in systems that support it)

**Comment by KayelGee** [comment]
I've thought about that and I'm not sure this is the right way to do it. In my option the base token is the pivot, if you need another pivot you can attach the token to another.

This isn't working with v&m because a token with an attached drawing can't be inside that drawing. So the solution you're describing is just trying to find a workaround for that. I'd rather have a solution where the token can be inside of a v&m drawing instead of a more complex workaround for that.

**Comment by KayelGee** [comment]
The next update will have an option to enable a base token to be inside of a v&m drawing without being moved by anything related to mlt/v&m which might solve the issue you're having.

**Comment by MarkPearce** [comment]
Only the problem of Z-fighting with other tokens would remain....

**Comment by KayelGee** [comment]
I think you'll love to hear of the https://github.com/theripper93/token-z module by theripper93 :D

**Comment by KayelGee** [comment]
I'll close this for now as I think with the new update and token-z module this should be in a working state

**Comment by MarkPearce** [comment]
Loving the new update.  Removing the redundant controller tokens now.
Thanks!
