### ISSUE TITLE
Feature Request - Is it possible to extend the api  token-target functionality to token-token ?

### ISSUE THREAD

**Issue by p4535992** [KayelGee/token-attacher#55]
I was updating my [Mount UP](https://github.com/p4535992/MountUp) module, but I noticed some strange behavior when using your macros [here](https://github.com/p4535992/MountUp/blob/master/src/module/tokenAttacherHelper.ts).
It is almost certainly due to the fact that you expect a "UserTarget" element and I instead provide a "Token" for the second argument.

Before getting back to my code I wanted to know if on your side it was complicated to add the following methods to your api for accept the token element or simply accept the string id of the token

- tokenAttacher.attachElementToToken(element, otherTokenOrStringId, suppresNotification=false)
- tokenAttacher.attachElementsToToken(element_array, otherTokenOrStringId, suppresNotification=false)
- tokenAttacher.detachElementFromToken(element, otherTokenOrStringId, suppressNotification=false)
- tokenAttacher.detachElementsFromToken(element_array, otherTokenOrStringId, suppressNotification=false)
- tokenAttacher.detachAllElementsFromToken(otherTokenOrStringId, suppressNotification=false)
- tokenAttacher.getAllAttachedElementsOfToken(otherTokenOrStringId, suppressNotification=false)
- tokenAttacher.getAllAttachedElementsByTypeOfToken(otherTokenOrStringId, type, suppressNotification=false)

**Comment by KayelGee** [comment]
The api doesn't have any assumptions about anything being a target or not. In fact there's no difference between a target from `Array.from(getGame().user.targets)` and a token. 

In the example macro I just used targets because that's how a user is able to select anything beside his own token. In your scripts you can actually do for example `await window['tokenAttacher'].attachElementToToken(riderToken, mountToken, true);` no problem. 

Also what you're suggesting for the api to accept an id instead of a token is actually how it works. You can either pass a token or it's id. 

So if some code of yours doesn't work, show me which part doesn't and I can maybe clear up your misunderstanding.

**Comment by p4535992** [comment]
Ty fort the clarification. I must be some mistake on  my side
