### ISSUE TITLE
setElementsLockStatus fails to unlock the selected token

### ISSUE THREAD

**Issue by paulohdsc** [KayelGee/token-attacher#59]
### Environment Details
* Foundry VTT: 0.8.9
* Game System: dnd5e 1.5.3
* How Are You Using Foundry: self-hosting on Node / Chrome 94.0.4606.81
* Modules Enabled?: only Token Attacher and dependencies

### Issue Description
I'm trying to use the **(TA)Mount Up!** macro and I noticed that the **setElementsLockStatus** function is not working as intended. The macro properly attachs the token to the targeted mount, but fails to set the selected token status as "unlocked: true".

I tried both `await tokenAttacher.setElementsLockStatus(token, false, true);` (the expected one) and `await tokenAttacher.setElementsLockStatus(token, true, true);` (just in case) with no success.

Best regards. Thanks for the module!

**Comment by KayelGee** [comment]
Maybe it's a misunderstanding because it works on my end.
When you attach a token to another base token(via the mount up macro for example) then you won't be able to select the token via rectangle selection or by clicking on it(you can still double click it). When you do `await tokenAttacher.setElementsLockStatus(token, false, true);` then you can select it via rectangle selection or by clicking on it.
