### ISSUE TITLE
How can I attach spell templates?

### ISSUE THREAD

**Issue by gravagehulk** [KayelGee/token-attacher#6]
I used to use Token Mold for attaching spell templates to characters. The dev informed me that he removed the feature because this module exists. I see no way to attach a spell template. I can't seem to select the template to attach it when the window is open.

**Comment by KayelGee** [comment]
You can either do it via macro or by using the module select tool everywhere.

**Comment by SabreRunner** [comment]
I still don't understand how to attach a template.

**Comment by KayelGee** [comment]
> I still don't understand how to attach a template.

The module https://foundryvtt.com/packages/select-tool-everywhere adds a select tool to templates, which is usually the most straight forward way. 
Since 4.0 you can also use the multi layer select tool, see https://github.com/KayelGee/token-attacher#usage look for "Attach elements on multiple layer with the rectangle select tool."
