### ISSUE TITLE
Quick Edit toggle button to use Foundry styling

### ISSUE THREAD

**Issue by LukasPrism** [KayelGee/token-attacher#79]
Just a trivial thing really, although it may help user interaction. The Quick Edit toggle button in the toolbar should probably be a regular toggle style button (ie. purple outline with a highlight when activated).

**Comment by KayelGee** [comment]
What do you mean by purple? Default foundry is using orange as a highlight.
I didn't bother with adding an actual toggle to the token controls ui, because it's relevant for different layers(that's why I chose to show the big notifier at the bottom of the screen). 
But I guess to make it consistent it should be an actual toggle. Should be simple enough to add.

**Comment by LukasPrism** [comment]
Hmm maybe it's something I have installed, but I've seen the same on most screenshots of foundry on the discord. Orange for currently selected tool, purple for off/on toggles.
<img width="91" alt="image" src="https://user-images.githubusercontent.com/104886594/174688982-311fd490-5778-4b97-a3ff-4cfe58041614.png">
The classes are 
#controls ol.control-tools > li.toggle
#controls ol.control-tools > li.toggle.active
#controls ol.control-tools > li.toggle:hover
