### ISSUE TITLE
Assigning a prototypeToken in foundry version 10.287/10.288 will only work correctly after a refresh(F5)

### ISSUE THREAD

**Issue by Noggog** [KayelGee/token-attacher#83]
I've got two tiles together to make a spell effect of sorts, and i've attached them to a token.   Seems like i can move it around and they all go just fine as expected.

Problem is when i try to make a 2nd one.   I modify the prototype token and click "Assign Token", which I've heard is how you "save" your attachments for reuse and eventual compendium storage.   When i drag out another actor from that prototype, though, i only get one set of tokens, which both actors control.

I feel like there's something I'm missing.

https://user-images.githubusercontent.com/24981326/195253864-943a667d-b039-49dd-aca9-0b0c5d7cc5db.mp4

Is this a bug?  Or is there a more appropriate way of making a prototype for reuse multiple times in the scene?

**Comment by KayelGee** [comment]
Are you on the current version of token attacher?

**Comment by KayelGee** [comment]
So I just looked again at this issue and I guess this is just a core issue I've reported. 
Since foundry version 10.287 you have to refresh the page after setting the prototypeToken.
I've no better solution as I tried everything I could come up with to solve this. So we have to wait for foundry to fix this.

**Comment by KayelGee** [comment]
should be fixed in the new release
