### ISSUE TITLE
Unable to Select an Attached Token without UI Open

### ISSUE THREAD

**Issue by illcom94** [KayelGee/token-attacher#95]
Once a token is attached to another token, you can't select the attached token unless the token attached UI is open. This causes issues if players need to control more than one token that are attached to the same or other tokens and want to access the Token Action HUD or other interfaces that need a token to be selected to interact with.

**Comment by dineshm72** [comment]
That is seemingly by design.  From the readme:

Attached elements can no longer be selected via the rectangle selection tool of each layer, unless the attach ui of the base token is open or you use the unlock feature. Attached elements can still be interacted with via double left or right click. Attached elements can no longer move independently of the base token. When dragging an prefab to the canvas the attached tiles will be sorted to the top(but still respect their z order inside the prefab).

**Comment by KayelGee** [comment]
yeah that is by design. Use unlock if you want to be able to select a token even when it's attached.
